name: flutter_focus_debugger
description: "Tools for inspecting and debugging focus behavior in Flutter apps."
version: 0.1.3
repository: https://github.com/Flutter-Bounty-Hunters/flutter_focus_debugger

environment:
  sdk: ^3.6.0 # 3.6.0 to avoid the stupid Dart auto formatting
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_test_goldens: ^0.0.7
  flutter_test_robots: ^0.0.24
