name: flutter_focus_debugger
description: "Tools for inspecting and debugging focus behavior in Flutter apps."
version: 0.1.0
repository: https://github.com/Flutter-Bounty-Hunters/flutter_focus_debugger

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
